name: Build Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  build-providers:
    uses: ./.github/workflows/build-providers.yaml
  coverage-build:
    runs-on: ubuntu-latest
    needs: build-providers
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: build/
          key: cally-test-providers
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install Provider Pacakges
        run: pip install build/**/*.tar.gz
      - name: Install Cally test dependencies
        run: pip install .[test]
      - name: Run Coverage
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml
          retention-days: 1
