name: Build Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  coverage-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip
      - name: Install Cally test dependencies
        run: pip install .[test]
      - name: Restore Provider Packages
        id: cache-providers
        uses: actions/cache@v4
        with:
          path: build/random/dist/CallyProvidersRandom-3.6.0.tar.gz
          key: cally-provider-random-3.6.0
      - uses: actions/setup-node@v4
        if: steps.cache-providers.outputs.cache-hit != 'true'
        with:
          node-version: "20"
      - name: Install cdktf-cli and build
        if: steps.cache-providers.outputs.cache-hit != 'true'
        run: |
          npm install cdktf-cli
          echo "$(pwd)/node_modules/.bin/" >> $GITHUB_PATH
          cally provider build --provider random --version 3.6.0
          (cd build/random && python -m build)
      - name: Install Provider Pacakge
        run: pip install build/random/dist/CallyProvidersRandom-3.6.0.tar.gz
      - name: Run Coverage
        run: |
          coverage run -m pytest
          coverage xml
      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage.xml
          path: coverage.xml
          retention-days: 1
