name: Test

on:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  build-providers:
    uses: ./.github/workflows/build-providers.yaml
  pytest:
    runs-on: ubuntu-latest
    needs: build-providers
    strategy:
      matrix:
        python: ["3.11"]
    steps:
      # Restore Provider Packages
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: build/random/dist/CallyProvidersRandom-3.6.0.tar.gz
          key: cally-provider-random-3.6.0
      - uses: actions/cache/restore@v3
        id: cache
        with:
          path: build/random/dist/CallyProvidersGoogle-5.21.0.tar.gz
          key: cally-provider-google-5.21.0

      # Cally Install
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - name: Install Provider Pacakges
        run: |
          pip install build/random/dist/CallyProvidersRandom-3.6.0.tar.gz
          pip install build/random/dist/CallyProvidersGoogle-5.21.0.tar.gz
      - name: Install Cally test dependencies
        run: pip install .[test]

      # Run Tests
      - name: Run Pytest
        run: pytest -v
