name: Test

on:
  workflow_call:
  push:
    branches-ignore:
      - main

jobs:
  build-providers:
    uses: ./.github/workflows/build-providers.yaml
  pytest:
    runs-on: ubuntu-latest
    needs: build-providers
    strategy:
      matrix:
        python: ["3.11"]
    env:
      UV_SYSTEM_PYTHON: true
    steps:
      # Restore Provider Packages
      - uses: actions/checkout@v4
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: build/
          key: cally-test-providers

      # Cally Install
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
      - uses: yezz123/setup-uv@v4
      - name: Install Provider Pacakges
        run: uv pip install build/**/*.tar.gz
      - name: Install Cally test dependencies
        run: uv pip install .[test]

      # Run Tests
      - name: Run Pytest
        run: pytest -v
